### ISSUE TITLE
Wabbitguy saved my bacon

### ISSUE THREAD

**Issue by adrianPerez** [wabbitguy/Anycubic_Kobra_Max#1]
Thank you so much for the profile. It saved my bacon. Cura kept spewing out gcode that led to bad prints on the Max. And your profiles saved me for a last minute project. Sorry to message in the issues, but github took away the ability to dm.

**Comment by wabbitguy** [comment]
@adrianPerez you're very welcome! Great to hear they might have saved a little frustration...

Mel
