### ISSUE TITLE
What nozzle is this set for?

### ISSUE THREAD

**Issue by Volsungare** [wabbitguy/Anycubic_Kobra_Max#2]
Is this set for a .4 ,mm nozzle? And what settings would I need to tweak to update this for a 0.6mm nozzle with PLA? We have one at my company and we just ordered a second one. But for the sake of print speed we are moving to a .06mm nozzle and plan on playing with layer heights between .2-.4 to find an optimal one.

**Comment by wabbitguy** [comment]
@Volsungare the profiles are set for 0.4mm nozzle. To change to a larger nozzle you'd need to adjust the 

Printer Settings --> Extruder nozzle size and the min/max the nozzle can do.
Print Settings --> Advanced --> all the widths (0.68mm to 0.72mm will be in the ball park)
Print Settings --> Speed --> range will be 40-55mm/s for the larger nozzles (test to find)

We've done a fair bit of testing with larger nozzles and sadly the 0.4 works the best. A 0.6 and 0.8 drool like a hot Saint Bernard. We were fighting stringing pretty badly and ended up using specific brands of filament to help with that. A better quality hot end may help with that, but, that also brings in its own brand of problems. I'd certainly be interested in hearing your results.
