### ISSUE TITLE
Texture-bed alignment issue

### ISSUE THREAD

**Issue by eccentricexit** [wabbitguy/Anycubic_Kobra_Max#3]
I just imported the PLA Profile, set the texture and bed model to the provided files.

As you can see below the bed and texture to not match. 

![image](https://github.com/wabbitguy/Kobra_Max_PRUSA_Profiles/assets/9872474/8cb37e56-306c-4eee-9f2a-45547ce9e05b)

Do you know what might be the problem?

I am running PrusaSlicer v2.6.0.

**Comment by wabbitguy** [comment]
@eccentricexit cool.  PRUSA Slicer has changed in their set up for the graphic and the STL file, I haven't been able to track down exactly what they want so removing the STL is what has worked just fine.

![Kobra_Bed](https://github.com/wabbitguy/Kobra_Max_PRUSA_Profiles/assets/8953419/bcb33ac9-e62d-4bd9-8c61-33c9277ee72c)
